const valueTraduccion = {
  id: 'ID',
  noEmpleado: 'Número de Empleado',
  nss: 'NSS',
  curp: 'CURP',
  rfc: 'RFC',
  blood: 'Tipo de Sangre',
  account: 'Cuenta Bancaria',
  emergencyContact: 'Contacto de Emergencia',
  positionId: 'Posición',
  admissionDate: 'Fecha de Admisión',
  active: 'Activo',
  emergencyNumber: 'Número de Emergencia',
  areaId: 'Área',
  quitDate: 'Fecha de Renuncia',
  bornLocation: 'Lugar de Nacimiento',
  genre: 'Género',
  sons: 'Hijos',
  clinicNo: 'Número de Clínica',
  email: 'Correo Electrónico',
  number: 'Número',
  direction: 'Dirección',
  bank: 'Banco',
  infonavitNo: 'Número de Infonavit',
  infonavitFee: 'Cuota de Infonavit',
  infonavitDiscount: 'Descuento de Infonavit',
  positionType: 'Tipo de Posición',
  cim: 'CIM',
  shift: 'Turno',
  nominaSalary: 'Salario Nómina',
  immsSalary: 'Salario IMSS',
  name: 'Nombre',
  paternalLastName: 'Apellido Paterno',
  maternalLastName: 'Apellido Materno',
  nationality: 'Nacionalidad',
  civilStatus: 'Estado Civil',
  bornDate: 'Fecha de Nacimiento',
  studies: 'Estudios',
  quitReason: 'Motivo de Renuncia',
  quitStatus: 'Estado de Renuncia',
  quitNotes: 'Notas de Renuncia',
  username: 'Nombre de Usuario',
  password: 'Contraseña',
  perm_assistance_areas: 'Permisos de Áreas de Asistencia',
  perm_users: 'Permisos de Usuarios',
  perm_assistance: 'Permisos de Asistencia',
  perm_productivity: 'Permisos de Productividad',
  perm_employees: 'Permisos de Empleados',
  perm_inventory: 'Permisos de Inventario',
  programation: 'Programación',
  jobpo: 'Job o PO',
  import: 'Importación',
  date: 'Fecha',
  due: 'Fecha',
  anydeskPW: 'Anydesk PW',
  lastMaintance: 'Último mantenimiento',
  owner: 'Usuario',
  docs: 'Documentación',
  code: 'Codigo',
  perm_structure: 'Permisos de Estructura',
  perm_it: 'Permisos de TI',
  perm_requisitions: 'Permisos de Requisiciones',
  perm_materialmovements: 'Permisos de Movimientos de Material',
  perm_inventorystats: 'Permisos de Estadísticas de Inventario',
  perm_petitions: 'Permisos de Peticiones',
  file: 'Archivo',
  location: 'Ubicación',
  description: 'Descripción',
  status: 'Estado',
  type: 'Tipo',
  model: 'Modelo',
  serial: 'Número de Serie',
  brand: 'Marca',
  category: 'Categoría',
  quantity: 'Cantidad',
  price: 'Precio',
  supplier: 'Proveedor',
  purchaseDate: 'Fecha de Compra',
  warranty: 'Garantía',
  notes: 'Notas',
  department: 'Departamento',
  position: 'Posición',
  phone: 'Teléfono',
  address: 'Dirección',
  city: 'Ciudad',
  state: 'Estado',
  country: 'País',
  zipCode: 'Código Postal',
  employeeId: 'ID de Empleado',
  start_date: 'Fecha de Inicio',
  end_date: 'Fecha de Fin',
  reason: 'Razón',
  comments: 'Comentarios',
  created_at: 'Creado el',
  updated_at: 'Actualizado el',
  created_by: 'Creado por',
  updated_by: 'Actualizado por',
  assigned_to: 'Asignado a',
  priority: 'Prioridad',
  due_date: 'Fecha de Vencimiento',
  completed_date: 'Fecha de Completado',
  percentage: 'Porcentaje',
  hours: 'Horas',
  minutes: 'Minutos',
  salary: 'Salario',
  bonus: 'Bono',
  deductions: 'Deducciones',
  totalSalary: 'Salario Total',
  paymentDate: 'Fecha de Pago',
  paymentMethod: 'Método de Pago',
  accountNumber: 'Número de Cuenta',
  bankName: 'Nombre del Banco',
  taxId: 'ID Fiscal',
  taxPercentage: 'Porcentaje de Impuesto',
  taxAmount: 'Monto de Impuesto',
  currency: 'Moneda',
  exchangeRate: 'Tipo de Cambio',
  totalAmount: 'Monto Total',
  subtotal: 'Subtotal',
  discount: 'Descuento',
  tax: 'Impuesto',
  shipping: 'Envío',
  trackingNumber: 'Número de Seguimiento',
  deliveryDate: 'Fecha de Entrega',
  deliveryAddress: 'Dirección de Entrega',
  invoiceNumber: 'Número de Factura',
  invoiceDate: 'Fecha de Factura',
  paymentStatus: 'Estado de Pago',
  orderNumber: 'Número de Orden',
  orderDate: 'Fecha de Orden',
  orderStatus: 'Estado de Orden',
  productId: 'ID de Producto',
  productName: 'Nombre de Producto',
  unitPrice: 'Precio Unitario',
  totalPrice: 'Precio Total',
  stockQuantity: 'Cantidad en Stock',
  minimum: 'Mínimo',
  locationId: 'Ubicación',
  warehouseId: 'Almacén',
  warehouseName: 'Nombre de Almacén',
  shelfLife: 'Vida Útil',
  expirationDate: 'Fecha de Expiración',
  manufacturingDate: 'Fecha de Fabricación',
  batchNumber: 'Número de Lote',
  inventoryId: 'ID de Inventario',
  movementType: 'Tipo de Movimiento',
  movementDate: 'Fecha de Movimiento',
  sourceLocation: 'Ubicación de Origen',
  destinationLocation: 'Ubicación de Destino',
  documentNumber: 'Número de Documento',
  documentDate: 'Fecha de Documento',
  documentType: 'Tipo de Documento',
  reference: 'Referencia',
  issue: 'Problema',
  resolution: 'Resolución',
  timeSpent: 'Tiempo Empleado',
};

export const getTraducction = (value: string | number) => {
  if (typeof value === 'number') value = value.toString();

  for (const key in valueTraduccion) {
    if (value.toLowerCase() === key.toLowerCase()) return valueTraduccion[key];
  }

  return value; // Return original value if no match found
};
