version: '3.8'

services:
  frontend:
    image: cst_frontend:latest  
    ports:
      - "3000:3000"  

  backend:
    image: cst_backend:latest  
    ports:
      - "5000:3000"  
    depends_on:
      - db  
      
  db:
    image: cst_postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5434:5432"