version: '3.8'

services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    image: cst_frontend:latest  
    ports:
      - "3000:3000"  
    profiles:
      - dev

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    image: cst_backend:latest  
    ports:
      - "5000:5000"  
    depends_on:
      - db  
    profiles:
      - dev
      
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5434:5432"
