version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: cst_frontend:latest  
    ports:
      - "80:3000"  
    profiles:
      - dev

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    image: cst_backend:latest  
    ports:
      - "5000:5000"  
    depends_on:
      - db  
    profiles:
      - dev
      
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data: