import { z } from 'zod';

const dateRegex = /^\d{4}-\d{2}-\d{2}$/;

export const weekSchema = z.object({
  date: z.string().refine((value) => dateRegex.test(value)),
});

export const editSchema = z.object({
  id: z.number(),
  '0code0': z.string().optional().nullable(),
  '0goal0': z.string().optional().nullable(),
  '0produced0': z.string().optional().nullable(),
  '0code1': z.string().optional().nullable(),
  '0goal1': z.string().optional().nullable(),
  '0produced1': z.string().optional().nullable(),
  '0code2': z.string().optional().nullable(),
  '0goal2': z.string().optional().nullable(),
  '0produced2': z.string().optional().nullable(),
  '0comment': z.string().optional().nullable(),
  '1code0': z.string().optional().nullable(),
  '1goal0': z.string().optional().nullable(),
  '1produced0': z.string().optional().nullable(),
  '1code1': z.string().optional().nullable(),
  '1goal1': z.string().optional().nullable(),
  '1produced1': z.string().optional().nullable(),
  '1code2': z.string().optional().nullable(),
  '1goal2': z.string().optional().nullable(),
  '1produced2': z.string().optional().nullable(),
  '2code0': z.string().optional().nullable(),
  '2goal0': z.string().optional().nullable(),
  '2produced0': z.string().optional().nullable(),
  '2code1': z.string().optional().nullable(),
  '2goal1': z.string().optional().nullable(),
  '2produced1': z.string().optional().nullable(),
  '2code2': z.string().optional().nullable(),
  '2goal2': z.string().optional().nullable(),
  '2produced2': z.string().optional().nullable(),
  '3code0': z.string().optional().nullable(),
  '3goal0': z.string().optional().nullable(),
  '3produced0': z.string().optional().nullable(),
  '3code1': z.string().optional().nullable(),
  '3goal1': z.string().optional().nullable(),
  '3produced1': z.string().optional().nullable(),
  '3code2': z.string().optional().nullable(),
  '3goal2': z.string().optional().nullable(),
  '3produced2': z.string().optional().nullable(),
  '4code0': z.string().optional().nullable(),
  '4goal0': z.string().optional().nullable(),
  '4produced0': z.string().optional().nullable(),
  '4code1': z.string().optional().nullable(),
  '4goal1': z.string().optional().nullable(),
  '4produced1': z.string().optional().nullable(),
  '4code2': z.string().optional().nullable(),
  '4goal2': z.string().optional().nullable(),
  '4produced2': z.string().optional().nullable(),
  assistanceId: z.string().optional().nullable(),
  '1comment': z.string().optional().nullable(),
  '2comment': z.string().optional().nullable(),
  '3comment': z.string().optional().nullable(),
  '4comment': z.string().optional().nullable(),
  name: z.string().optional().nullable(),
  noEmpleado: z.string().optional().nullable(),
  areaId: z.string().optional().nullable(),
  positionId: z.string().optional().nullable(),
  incidenceId0: z.string().optional().nullable(),
  incidenceId1: z.string().optional().nullable(),
  incidenceId2: z.string().optional().nullable(),
  incidenceId3: z.string().optional().nullable(),
  incidenceId4: z.string().optional().nullable(),
  '0average': z.string().optional().nullable(),
  '1average': z.string().optional().nullable(),
  '2average': z.string().optional().nullable(),
  '3average': z.string().optional().nullable(),
  '4average': z.string().optional().nullable(),
});
